apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: appservices.rbt.example.com
spec:
  group: rbt.example.com
  names:
    kind: Appservice
    listKind: AppserviceList
    plural: appservices
    singular: appservice
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Appservice is the Schema for the appservices API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: AppserviceSpec defines the desired state of Appservice
            type: object
          status:
            description: AppserviceStatus defines the observed state of Appservice
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
